name: Telegraf container

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull non cached images
      run: |
        docker pull buildpack-deps:buster-curl
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build full image
      run: |
        docker build . -t telegrafconfig

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: telegrafconfig # Provide only Docker image name, tag will be automatically set to latest

    - name: CapRover Image Deploy
      uses: AlexxNB/caprover-action@v1
      with:
        server: '${{secrets.CAPROVER_ROOT}}'
        password: '${{ secrets.CAPROVER_PASSWORD}}'
        appname: 'timmeeytelegraf'
        image: docker.pkg.github.com/timmeey/telegraf_configs/telegrafconfig:latest
        
